name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: ShellCheck
        run: |
          set -euo pipefail
          shellcheck -x \
            .github/workflows/assets/env.sh \
            .github/workflows/assets/lib.sh \
            scripts/*.sh

      - name: actionlint
        run: |
          set -euo pipefail
          bash <(curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
